<?php

namespace Database\Seeders;

use App\Models\Product;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Product::insert([
            [
                'brand_id' => 1,
                'model' => "Xiaomi 14 Pro",
                'price' => 15000000,
                'performance' => 1450000,
                'battery' => 5000,
                'camera' => 200,
                'storage' => 256,
            ],
            [
                'brand_id' => 1,
                'model' => "Redmi Note 13 Pro+",
                'price' => 6500000,
                'performance' => 850000,
                'battery' => 5100,
                'camera' => 200,
                'storage' => 128,
            ],
            [
                'brand_id' => 1,
                'model' => "Poco F6 Pro",
                'price' => 9000000,
                'performance' => 1200000,
                'battery' => 5000,
                'camera' => 108,
                'storage' => 256,
            ],
            [
                'brand_id' => 1,
                'model' => "Redmi K70",
                'price' => 8000000,
                'performance' => 1300000,
                'battery' => 5500,
                'camera' => 50,
                'storage' => 256,
            ],
            [
                'brand_id' => 1,
                'model' => "Xiaomi 13T",
                'price' => 7500000,
                'performance' => 950000,
                'battery' => 5000,
                'camera' => 50,
                'storage' => 256,
            ],
            [
                'brand_id' => 1,
                'model' => "Redmi Note 12 Turbo",
                'price' => 5000000,
                'performance' => 700000,
                'battery' => 5000,
                'camera' => 64,
                'storage' => 128,
            ],
            [
                'brand_id' => 1,
                'model' => "Poco X6 Pro",
                'price' => 6000000,
                'performance' => 850000,
                'battery' => 5000,
                'camera' => 64,
                'storage' => 256,
            ],
            [
                'brand_id' => 1,
                'model' => "Black Shark 6 Pro",
                'price' => 11000000,
                'performance' => 1400000,
                'battery' => 5000,
                'camera' => 64,
                'storage' => 256,
            ],
            [
                'brand_id' => 1,
                'model' => "Mix Fold 3",
                'price' => 20000000,
                'performance' => 1500000,
                'battery' => 4800,
                'camera' => 50,
                'storage' => 512,
            ],
            [
                'brand_id' => 1,
                'model' => "Redmi A3",
                'price' => 2500000,
                'performance' => 250000,
                'battery' => 5000,
                'camera' => 13,
                'storage' => 64,
            ],
            [
                'brand_id' => 2,
                'model' => "Galaxy S24 Ultra",
                'price' => 22000000,
                'performance' => 1600000,
                'battery' => 5000,
                'camera' => 200,
                'storage' => 512,
            ],
            [
                'brand_id' => 2,
                'model' => "Galaxy S23 FE",
                'price' => 10000000,
                'performance' => 950000,
                'battery' => 4500,
                'camera' => 50,
                'storage' => 256,
            ],
            [
                'brand_id' => 2,
                'model' => "Galaxy A54 5G",
                'price' => 7200000,
                'performance' => 550000,
                'battery' => 5000,
                'camera' => 50,
                'storage' => 128,
            ],
            [
                'brand_id' => 2,
                'model' => "Galaxy M55",
                'price' => 6000000,
                'performance' => 500000,
                'battery' => 5000,
                'camera' => 108,
                'storage' => 128,
            ],
            [
                'brand_id' => 2,
                'model' => "Galaxy Z Fold 5",
                'price' => 25000000,
                'performance' => 1400000,
                'battery' => 4400,
                'camera' => 50,
                'storage' => 512,
            ],
            [
                'brand_id' => 2,
                'model' => "Galaxy Z Flip 5",
                'price' => 15000000,
                'performance' => 1200000,
                'battery' => 3700,
                'camera' => 12,
                'storage' => 256,
            ],
            [
                'brand_id' => 2,
                'model' => "Galaxy A34",
                'price' => 5500000,
                'performance' => 450000,
                'battery' => 5000,
                'camera' => 48,
                'storage' => 128,
            ],
            [
                'brand_id' => 2,
                'model' => "Galaxy F54",
                'price' => 5000000,
                'performance' => 500000,
                'battery' => 6000,
                'camera' => 108,
                'storage' => 256,
            ],
            [
                'brand_id' => 2,
                'model' => "Galaxy Tab S9 Ultra",
                'price' => 18000000,
                'performance' => 1300000,
                'battery' => 11200,
                'camera' => 13,
                'storage' => 512,
            ],
            [
                'brand_id' => 2,
                'model' => "Galaxy XCover 6",
                'price' => 4000000,
                'performance' => 300000,
                'battery' => 4050,
                'camera' => 50,
                'storage' => 128,
            ],
            [
                'brand_id' => 3,
                'model' => "Find X7 Ultra",
                'price' => 18000000,
                'performance' => 1550000,
                'battery' => 5000,
                'camera' => 200,
                'storage' => 512,
            ],
            [
                'brand_id' => 3,
                'model' => "Reno 11 Pro",
                'price' => 8500000,
                'performance' => 700000,
                'battery' => 4700,
                'camera' => 50,
                'storage' => 256,
            ],
            [
                'brand_id' => 3,
                'model' => "A98 5G",
                'price' => 5000000,
                'performance' => 450000,
                'battery' => 5000,
                'camera' => 64,
                'storage' => 128,
            ],
            [
                'brand_id' => 3,
                'model' => "Find N3 Flip",
                'price' => 12000000,
                'performance' => 1100000,
                'battery' => 4300,
                'camera' => 50,
                'storage' => 256,
            ],
            [
                'brand_id' => 3,
                'model' => "K11x",
                'price' => 3500000,
                'performance' => 350000,
                'battery' => 5000,
                'camera' => 108,
                'storage' => 128,
            ],
            [
                'brand_id' => 3,
                'model' => "A78 5G",
                'price' => 4500000,
                'performance' => 400000,
                'battery' => 5000,
                'camera' => 50,
                'storage' => 128,
            ],
            [
                'brand_id' => 3,
                'model' => "Reno 10 Pro+",
                'price' => 9000000,
                'performance' => 800000,
                'battery' => 4700,
                'camera' => 50,
                'storage' => 256,
            ],
            [
                'brand_id' => 3,
                'model' => "A58",
                'price' => 3000000,
                'performance' => 250000,
                'battery' => 5000,
                'camera' => 13,
                'storage' => 64,
            ],
            [
                'brand_id' => 3,
                'model' => "Find X6 Pro",
                'price' => 16000000,
                'performance' => 1450000,
                'battery' => 5000,
                'camera' => 50,
                'storage' => 512,
            ],
            [
                'brand_id' => 3,
                'model' => "F27 Pro+",
                'price' => 6000000,
                'performance' => 550000,
                'battery' => 5000,
                'camera' => 108,
                'storage' => 256,
            ],
            [
                'brand_id' => 4,
                'model' => "X100 Pro",
                'price' => 16500000,
                'performance' => 1500000,
                'battery' => 5400,
                'camera' => 200,
                'storage' => 512,
            ],
            [
                'brand_id' => 4,
                'model' => "V30 Pro",
                'price' => 9000000,
                'performance' => 750000,
                'battery' => 5000,
                'camera' => 50,
                'storage' => 256,
            ],
            [
                'brand_id' => 4,
                'model' => "iQOO 12",
                'price' => 11000000,
                'performance' => 1400000,
                'battery' => 5000,
                'camera' => 50,
                'storage' => 256,
            ],
            [
                'brand_id' => 4,
                'model' => "V27",
                'price' => 7000000,
                'performance' => 600000,
                'battery' => 4600,
                'camera' => 50,
                'storage' => 256,
            ],
            [
                'brand_id' => 4,
                'model' => "T2 Pro",
                'price' => 5000000,
                'performance' => 450000,
                'battery' => 4600,
                'camera' => 64,
                'storage' => 128,
            ],
            [
                'brand_id' => 4,
                'model' => "Y78+",
                'price' => 4000000,
                'performance' => 350000,
                'battery' => 5000,
                'camera' => 50,
                'storage' => 128,
            ],
            [
                'brand_id' => 4,
                'model' => "X90 Pro",
                'price' => 14000000,
                'performance' => 1350000,
                'battery' => 4870,
                'camera' => 50,
                'storage' => 256,
            ],
            [
                'brand_id' => 4,
                'model' => "iQOO Neo 9 Pro",
                'price' => 8000000,
                'performance' => 950000,
                'battery' => 5160,
                'camera' => 50,
                'storage' => 256,
            ],
            [
                'brand_id' => 4,
                'model' => "Y36",
                'price' => 3000000,
                'performance' => 250000,
                'battery' => 5000,
                'camera' => 50,
                'storage' => 128,
            ],
            [
                'brand_id' => 4,
                'model' => "S18e",
                'price' => 4500000,
                'performance' => 400000,
                'battery' => 4800,
                'camera' => 50,
                'storage' => 128,
            ],
            [
                'brand_id' => 5,
                'model' => "GT 5 Pro",
                'price' => 12000000,
                'performance' => 1300000,
                'battery' => 5400,
                'camera' => 50,
                'storage' => 256,
            ],
            [
                'brand_id' => 5,
                'model' => "Narzo 60 Pro",
                'price' => 5500000,
                'performance' => 600000,
                'battery' => 5000,
                'camera' => 108,
                'storage' => 128,
            ],
            [
                'brand_id' => 5,
                'model' => "11 Pro+",
                'price' => 8000000,
                'performance' => 750000,
                'battery' => 5000,
                'camera' => 200,
                'storage' => 256,
            ],
            [
                'brand_id' => 5,
                'model' => "C65",
                'price' => 2500000,
                'performance' => 200000,
                'battery' => 5000,
                'camera' => 50,
                'storage' => 128,
            ],
            [
                'brand_id' => 5,
                'model' => "GT Neo 6",
                'price' => 9000000,
                'performance' => 1100000,
                'battery' => 5500,
                'camera' => 50,
                'storage' => 256,
            ],
            [
                'brand_id' => 5,
                'model' => "10 Pro",
                'price' => 4000000,
                'performance' => 350000,
                'battery' => 5000,
                'camera' => 108,
                'storage' => 128,
            ],
            [
                'brand_id' => 5,
                'model' => "X9 Pro",
                'price' => 6000000,
                'performance' => 650000,
                'battery' => 4500,
                'camera' => 64,
                'storage' => 128,
            ],
            [
                'brand_id' => 5,
                'model' => "V50",
                'price' => 3500000,
                'performance' => 300000,
                'battery' => 5000,
                'camera' => 13,
                'storage' => 64,
            ],
            [
                'brand_id' => 5,
                'model' => "GT 2 Pro",
                'price' => 10000000,
                'performance' => 950000,
                'battery' => 5000,
                'camera' => 50,
                'storage' => 256,
            ],
            [
                'brand_id' => 5,
                'model' => "C55",
                'price' => 3000000,
                'performance' => 250000,
                'battery' => 5000,
                'camera' => 64,
                'storage' => 128,
            ],
            [
                'brand_id' => 6,
                'model' => "12",
                'price' => 17000000,
                'performance' => 1500000,
                'battery' => 5400,
                'camera' => 50,
                'storage' => 256,
            ],
            [
                'brand_id' => 6,
                'model' => "Nord 3",
                'price' => 7000000,
                'performance' => 800000,
                'battery' => 5000,
                'camera' => 50,
                'storage' => 128,
            ],
            [
                'brand_id' => 6,
                'model' => "11R",
                'price' => 9000000,
                'performance' => 950000,
                'battery' => 5000,
                'camera' => 50,
                'storage' => 256,
            ],
            [
                'brand_id' => 6,
                'model' => "Nord CE 4",
                'price' => 5000000,
                'performance' => 550000,
                'battery' => 5500,
                'camera' => 64,
                'storage' => 128,
            ],
            [
                'brand_id' => 6,
                'model' => "10T",
                'price' => 6000000,
                'performance' => 700000,
                'battery' => 4800,
                'camera' => 50,
                'storage' => 128,
            ],
            [
                'brand_id' => 6,
                'model' => "Pad",
                'price' => 8000000,
                'performance' => 850000,
                'battery' => 9510,
                'camera' => 13,
                'storage' => 256,
            ],
            [
                'brand_id' => 6,
                'model' => "Nord N30",
                'price' => 3500000,
                'performance' => 300000,
                'battery' => 5000,
                'camera' => 108,
                'storage' => 128,
            ],
            [
                'brand_id' => 6,
                'model' => "Open",
                'price' => 18000000,
                'performance' => 1400000,
                'battery' => 4800,
                'camera' => 48,
                'storage' => 512,
            ],
            [
                'brand_id' => 6,
                'model' => "9RT",
                'price' => 4500000,
                'performance' => 500000,
                'battery' => 4500,
                'camera' => 50,
                'storage' => 128,
            ],
            [
                'brand_id' => 6,
                'model' => "8T",
                'price' => 3000000,
                'performance' => 350000,
                'battery' => 4500,
                'camera' => 48,
                'storage' => 128,
            ],
            [
                'brand_id' => 7,
                'model' => "ROG Phone 8",
                'price' => 20000000,
                'performance' => 1600000,
                'battery' => 5500,
                'camera' => 50,
                'storage' => 512,
            ],
            [
                'brand_id' => 7,
                'model' => "Zenfone 11 Ultra",
                'price' => 13000000,
                'performance' => 1400000,
                'battery' => 5000,
                'camera' => 200,
                'storage' => 256,
            ],
            [
                'brand_id' => 7,
                'model' => "ROG Phone 7",
                'price' => 15000000,
                'performance' => 1450000,
                'battery' => 6000,
                'camera' => 50,
                'storage' => 512,
            ],
            [
                'brand_id' => 7,
                'model' => "Zenfone 10",
                'price' => 9000000,
                'performance' => 950000,
                'battery' => 4300,
                'camera' => 200,
                'storage' => 256,
            ],
            [
                'brand_id' => 7,
                'model' => "TUF Gaming F15",
                'price' => 7000000,
                'performance' => 800000,
                'battery' => 6000,
                'camera' => 50,
                'storage' => 128,
            ],
            [
                'brand_id' => 7,
                'model' => "ROG Phone 6D",
                'price' => 12000000,
                'performance' => 1300000,
                'battery' => 6000,
                'camera' => 50,
                'storage' => 512,
            ],
            [
                'brand_id' => 7,
                'model' => "Zenfone 9",
                'price' => 6000000,
                'performance' => 700000,
                'battery' => 4300,
                'camera' => 120,
                'storage' => 128,
            ],
            [
                'brand_id' => 7,
                'model' => "ROG Phone 5s",
                'price' => 8000000,
                'performance' => 900000,
                'battery' => 6000,
                'camera' => 64,
                'storage' => 256,
            ],
            [
                'brand_id' => 7,
                'model' => "ExpertBook B5",
                'price' => 5000000,
                'performance' => 300000,
                'battery' => 5000,
                'camera' => 13,
                'storage' => 128,
            ],
            [
                'brand_id' => 7,
                'model' => "VivoBook 15",
                'price' => 4000000,
                'performance' => 200000,
                'battery' => 5000,
                'camera' => 8,
                'storage' => 128,
            ],
            [
                'brand_id' => 8,
                'model' => "Edge 40 Ultra",
                'price' => 14000000,
                'performance' => 1350000,
                'battery' => 4600,
                'camera' => 200,
                'storage' => 512,
            ],
            [
                'brand_id' => 8,
                'model' => "Moto G84",
                'price' => 4000000,
                'performance' => 400000,
                'battery' => 5000,
                'camera' => 50,
                'storage' => 128,
            ],
            [
                'brand_id' => 8,
                'model' => "Edge 30 Fusion",
                'price' => 6000000,
                'performance' => 650000,
                'battery' => 4400,
                'camera' => 50,
                'storage' => 128,
            ],
            [
                'brand_id' => 8,
                'model' => "Razr 40 Ultra",
                'price' => 12000000,
                'performance' => 1100000,
                'battery' => 3800,
                'camera' => 12,
                'storage' => 256,
            ],
            [
                'brand_id' => 8,
                'model' => "Edge 30 Neo",
                'price' => 3500000,
                'performance' => 300000,
                'battery' => 4020,
                'camera' => 64,
                'storage' => 128,
            ],
            [
                'brand_id' => 8,
                'model' => "Moto G73",
                'price' => 3000000,
                'performance' => 250000,
                'battery' => 5000,
                'camera' => 50,
                'storage' => 128,
            ],
            [
                'brand_id' => 8,
                'model' => "Edge 20 Lite",
                'price' => 2500000,
                'performance' => 200000,
                'battery' => 5000,
                'camera' => 108,
                'storage' => 128,
            ],
            [
                'brand_id' => 8,
                'model' => "Defy 2024",
                'price' => 5000000,
                'performance' => 450000,
                'battery' => 5000,
                'camera' => 50,
                'storage' => 128,
            ],
            [
                'brand_id' => 8,
                'model' => "Moto E40",
                'price' => 2000000,
                'performance' => 150000,
                'battery' => 5000,
                'camera' => 48,
                'storage' => 64,
            ],
            [
                'brand_id' => 8,
                'model' => "One 5G Ace",
                'price' => 3500000,
                'performance' => 300000,
                'battery' => 5000,
                'camera' => 48,
                'storage' => 128,
            ],
            [
                'brand_id' => 10,
                'model' => "Pixel 8 Pro",
                'price' => 18000000,
                'performance' => 1200000,
                'battery' => 5050,
                'camera' => 50,
                'storage' => 128,
            ],
            [
                'brand_id' => 10,
                'model' => "Pixel 8",
                'price' => 12000000,
                'performance' => 1100000,
                'battery' => 4575,
                'camera' => 50,
                'storage' => 128,
            ],
            [
                'brand_id' => 10,
                'model' => "Pixel 7a",
                'price' => 7000000,
                'performance' => 850000,
                'battery' => 4385,
                'camera' => 64,
                'storage' => 128,
            ],
            [
                'brand_id' => 10,
                'model' => "Pixel Fold",
                'price' => 20000000,
                'performance' => 1300000,
                'battery' => 4800,
                'camera' => 48,
                'storage' => 256,
            ],
            [
                'brand_id' => 10,
                'model' => "Pixel 6a",
                'price' => 5000000,
                'performance' => 600000,
                'battery' => 4410,
                'camera' => 12,
                'storage' => 128,
            ],
            [
                'brand_id' => 11,
                'model' => "Magic 6 Pro",
                'price' => 16000000,
                'performance' => 1450000,
                'battery' => 5600,
                'camera' => 200,
                'storage' => 512,
            ],
            [
                'brand_id' => 11,
                'model' => "X9b",
                'price' => 6000000,
                'performance' => 650000,
                'battery' => 5800,
                'camera' => 108,
                'storage' => 256,
            ],
            [
                'brand_id' => 11,
                'model' => "90 Lite",
                'price' => 3500000,
                'performance' => 300000,
                'battery' => 4500,
                'camera' => 100,
                'storage' => 128,
            ],
            [
                'brand_id' => 11,
                'model' => "Magic 5 Lite",
                'price' => 4000000,
                'performance' => 350000,
                'battery' => 5100,
                'camera' => 64,
                'storage' => 128,
            ],
            [
                'brand_id' => 11,
                'model' => "70 Pro",
                'price' => 5000000,
                'performance' => 450000,
                'battery' => 4800,
                'camera' => 54,
                'storage' => 256,
            ],
            [
                'brand_id' => 12,
                'model' => "Zero 30 5G",
                'price' => 5000000,
                'performance' => 500000,
                'battery' => 5000,
                'camera' => 108,
                'storage' => 256,
            ],
            [
                'brand_id' => 12,
                'model' => "Note 40 Pro",
                'price' => 4000000,
                'performance' => 350000,
                'battery' => 5000,
                'camera' => 108,
                'storage' => 128,
            ],
            [
                'brand_id' => 12,
                'model' => "Hot 30i",
                'price' => 2000000,
                'performance' => 150000,
                'battery' => 5000,
                'camera' => 13,
                'storage' => 64,
            ],
            [
                'brand_id' => 12,
                'model' => "Smart 8",
                'price' => 1500000,
                'performance' => 100000,
                'battery' => 5000,
                'camera' => 13,
                'storage' => 64,
            ],
            [
                'brand_id' => 12,
                'model' => "GT 10 Pro",
                'price' => 4500000,
                'performance' => 400000,
                'battery' => 5000,
                'camera' => 108,
                'storage' => 128,
            ],
            [
                'brand_id' => 13,
                'model' => "Camon 30 Pro",
                'price' => 4500000,
                'performance' => 400000,
                'battery' => 5000,
                'camera' => 200,
                'storage' => 256,
            ],
            [
                'brand_id' => 13,
                'model' => "Phantom V Flip",
                'price' => 8000000,
                'performance' => 700000,
                'battery' => 4000,
                'camera' => 64,
                'storage' => 256,
            ],
            [
                'brand_id' => 13,
                'model' => "Pova 5 Pro",
                'price' => 3000000,
                'performance' => 250000,
                'battery' => 6000,
                'camera' => 50,
                'storage' => 128,
            ],
            [
                'brand_id' => 13,
                'model' => "Spark 20",
                'price' => 1800000,
                'performance' => 100000,
                'battery' => 5000,
                'camera' => 50,
                'storage' => 128,
            ],
            [
                'brand_id' => 13,
                'model' => "Megabook T1",
                'price' => 5000000,
                'performance' => 0,
                'battery' => 7000,
                'camera' => 0,
                'storage' => 256,
            ],
            [
                'brand_id' => 14,
                'model' => "XR21",
                'price' => 7000000,
                'performance' => 600000,
                'battery' => 4800,
                'camera' => 64,
                'storage' => 128,
            ],
            [
                'brand_id' => 14,
                'model' => "G42",
                'price' => 3000000,
                'performance' => 300000,
                'battery' => 5000,
                'camera' => 50,
                'storage' => 128,
            ],
            [
                'brand_id' => 14,
                'model' => "X30 5G",
                'price' => 5000000,
                'performance' => 450000,
                'battery' => 4200,
                'camera' => 50,
                'storage' => 128,
            ],
            [
                'brand_id' => 14,
                'model' => "C32",
                'price' => 1500000,
                'performance' => 100000,
                'battery' => 5000,
                'camera' => 50,
                'storage' => 64,
            ],
            [
                'brand_id' => 14,
                'model' => "G22",
                'price' => 2000000,
                'performance' => 150000,
                'battery' => 5050,
                'camera' => 50,
                'storage' => 128,
            ],
            [
                'brand_id' => 15,
                'model' => "Xperia 1 V",
                'price' => 25000000,
                'performance' => 1400000,
                'battery' => 5000,
                'camera' => 48,
                'storage' => 256,
            ],
            [
                'brand_id' => 15,
                'model' => "Xperia 10 V",
                'price' => 8000000,
                'performance' => 500000,
                'battery' => 5000,
                'camera' => 48,
                'storage' => 128,
            ],
            [
                'brand_id' => 15,
                'model' => "Xperia 5 V",
                'price' => 10000000,
                'performance' => 950000,
                'battery' => 5000,
                'camera' => 48,
                'storage' => 128,
            ],
            [
                'brand_id' => 15,
                'model' => "Xperia Pro-I",
                'price' => 18000000,
                'performance' => 1200000,
                'battery' => 4500,
                'camera' => 50,
                'storage' => 512,
            ],
            [
                'brand_id' => 15,
                'model' => "Xperia Ace IV",
                'price' => 5000000,
                'performance' => 400000,
                'battery' => 5000,
                'camera' => 12,
                'storage' => 128,
            ],
            [
                'brand_id' => 16,
                'model' => "Key2 (2024)",
                'price' => 6000000,
                'performance' => 400000,
                'battery' => 4000,
                'camera' => 16,
                'storage' => 128,
            ],
            [
                'brand_id' => 17,
                'model' => "FP5",
                'price' => 5000000,
                'performance' => 350000,
                'battery' => 4200,
                'camera' => 50,
                'storage' => 128,
            ],
            [
                'brand_id' => 18,
                'model' => "Leitz Phone 3",
                'price' => 30000000,
                'performance' => 1200000,
                'battery' => 5000,
                'camera' => 47,
                'storage' => 256,
            ],
            [
                'brand_id' => 19,
                'model' => "Aquos R8",
                'price' => 10000000,
                'performance' => 900000,
                'battery' => 4570,
                'camera' => 50,
                'storage' => 128,
            ],
            [
                'brand_id' => 20,
                'model' => "Nubia Z60 Ultra",
                'price' => 15000000,
                'performance' => 1450000,
                'battery' => 6000,
                'camera' => 64,
                'storage' => 512,
            ],
            [
                'brand_id' => 20,
                'model' => "Axon 50 Ultra",
                'price' => 10000000,
                'performance' => 1000000,
                'battery' => 5000,
                'camera' => 200,
                'storage' => 256,
            ],
            [
                'brand_id' => 20,
                'model' => "Blade V50",
                'price' => 3000000,
                'performance' => 250000,
                'battery' => 5000,
                'camera' => 50,
                'storage' => 128,
            ],
            [
                'brand_id' => 21,
                'model' => "Legion Y90",
                'price' => 12000000,
                'performance' => 1300000,
                'battery' => 5600,
                'camera' => 64,
                'storage' => 512,
            ],
            [
                'brand_id' => 21,
                'model' => "Moto Tab G70",
                'price' => 3000000,
                'performance' => 200000,
                'battery' => 7700,
                'camera' => 13,
                'storage' => 128,
            ],
            [
                'brand_id' => 21,
                'model' => "K13 Note",
                'price' => 1500000,
                'performance' => 100000,
                'battery' => 5000,
                'camera' => 13,
                'storage' => 32,
            ],
            [
                'brand_id' => 22,
                'model' => "P60 Pro",
                'price' => 14000000,
                'performance' => 900000,
                'battery' => 4815,
                'camera' => 48,
                'storage' => 256,
            ],
            [
                'brand_id' => 22,
                'model' => "Nova 12",
                'price' => 6000000,
                'performance' => 600000,
                'battery' => 4600,
                'camera' => 50,
                'storage' => 256,
            ],
            [
                'brand_id' => 22,
                'model' => "Mate X5",
                'price' => 22000000,
                'performance' => 1100000,
                'battery' => 5060,
                'camera' => 50,
                'storage' => 512,
            ],
            [
                'brand_id' => 22,
                'model' => "Y70",
                'price' => 3000000,
                'performance' => 250000,
                'battery' => 5000,
                'camera' => 50,
                'storage' => 128,
            ],
            [
                'brand_id' => 22,
                'model' => "P50 Pocket",
                'price' => 10000000,
                'performance' => 800000,
                'battery' => 4000,
                'camera' => 40,
                'storage' => 256,
            ],
            [
                'brand_id' => 23,
                'model' => "21 Pro",
                'price' => 11000000,
                'performance' => 1250000,
                'battery' => 5050,
                'camera' => 200,
                'storage' => 512,
            ],
            [
                'brand_id' => 23,
                'model' => "20",
                'price' => 5000000,
                'performance' => 700000,
                'battery' => 4700,
                'camera' => 50,
                'storage' => 128,
            ],
            [
                'brand_id' => 23,
                'model' => "18X",
                'price' => 4000000,
                'performance' => 500000,
                'battery' => 4300,
                'camera' => 64,
                'storage' => 128,
            ],
            [
                'brand_id' => 24,
                'model' => "9 Pro",
                'price' => 13000000,
                'performance' => 1500000,
                'battery' => 6500,
                'camera' => 50,
                'storage' => 512,
            ],
            [
                'brand_id' => 24,
                'model' => "8S Pro+",
                'price' => 12000000,
                'performance' => 1400000,
                'battery' => 6000,
                'camera' => 64,
                'storage' => 512,
            ],
            [
                'brand_id' => 25,
                'model' => "5 Pro",
                'price' => 9000000,
                'performance' => 1200000,
                'battery' => 4650,
                'camera' => 108,
                'storage' => 256,
            ],
            [
                'brand_id' => 25,
                'model' => "4 Pro",
                'price' => 6000000,
                'performance' => 900000,
                'battery' => 4500,
                'camera' => 64,
                'storage' => 128,
            ],
        ]);
    }
}
